src/SDG_Backend/BlogPosts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):

    title = StringField('Title',validators=[DataRequired()])
    text = TextAreaField('Blog Text',validators=[DataRequired()])
    submit = SubmitField('Post')

    

src/SDG_Backend/BlogPosts/views.py
from flask import render_template,url_for,request,redirect,flash,Blueprint
from flask_login import current_user,login_required
from SDG_Backend import db
from SDG_Backend.models import BlogPost
from SDG_Backend.BlogPosts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

# create blogpost
@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,text=form.text.data,youth_id=current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created!")
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)

# view blogpost
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,date=blog_post.date,post=blog_post)

# update blogpost
@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):

    blog_post = blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post.title = form.title.data,
        blog_post.text = form.text.data

        db.session.commit()
        flash("Blog Post Updated!")
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post_id))

    elif request.method == 'GET':

        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html',title='Updating',form=form)

# delete blogpost
@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):

    blog_post = blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()

    flash("Blog Post has been deleted!")
    return redirect(url_for('core.index'))

src/SDG_Backend/Core/views.py
from flask import render_template,request,Blueprint,abort
from flask_login import login_user,current_user,logout_user,login_required
from SDG_Backend.models import BlogPost

core = Blueprint('core',__name__)

# add homepage for everyone
@core.route('/')
def index():

    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)

    return render_template('Core/index.html',blog_posts=blog_posts)


# add about us view
@core.route('/info')
def info():
    return render_template('Core/info.html')


# add youth dashboard view
@core.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('Core/dashboard.html', title="Dashboard")


# add sponsor dashboard view
@core.route('/sponsor_dashboard')
@login_required
def sponsor_dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('Core/sponsor_dashboard.html', title="Sponsor Dashboard")


# add admin dashboard view
@core.route('/admin/dashboard')
@login_required
def admin_dashboard():
    # prevent non-admins from accessing the page
    if not current_user.username == 'admin':
        abort(403)

    return render_template('Core/admin_dashboard.html', title="Admin Dashboard")

src/SDG_Backend/Sponsors/views.py
from flask import render_template,request,url_for,redirect,Blueprint,flash
from flask_login import login_user,current_user,logout_user,login_required
from .. import db
from ..models import Sponsor,BlogPost
from .forms import LoginForm,RegistrationForm,UpdateSponsorForm
from .picture_handler import add_profile_pic

sponsors = Blueprint('sponsors',__name__)

# Register
@sponsors.route('/register',methods=['GET','POST'])
def register():

    form = RegistrationForm()

    if form.validate_on_submit():
        sponsor = Sponsor(email=form.email.data,username=form.username.data,firstname=form.firstname.data,
                            lastname=form.lastname.data,password=form.password.data,phone_number=form.phone_number.data)

        db.session.add(sponsor)
        db.session.commit()
        flash('Thank you for registering!')
        return redirect(url_for('sponsors.login'))

    return render_template('Sponsor/register.html',form=form)

# Login
@sponsors.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()

    if form.validate_on_submit():
        sponsor = Sponsor.query.filter_by(email=form.email.data).first()

        if sponsor.check_password(form.password.data) and sponsor is not None:
            login_user(sponsor)
            flash('Log in Successful!')

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('sponsors.sponsors_dashboard')

            return redirect(next)

        else:
            flash('Invalid email or password.')

    return render_template('Sponsor/login.html',form=form)

# Logout
@sponsors.route('/logout')
def logout():

    logout_user()
    flash('You have successfully been logged out.')

    return redirect(url_for('core.index'))

# Account
@sponsors.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateSponsorForm()

    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data

        current_user.date_of_birth=form.date_of_birth.data
        current_user.state_of_origin=form.state_of_origin.data
        current_user.local_govt=form.local_govt.data
        current_user.address=form.address.data
        current_user.reason_for_donating=form.reason_for_donating.data

        db.session.commit()
        flash('Sponsor Account Updated!')
        return redirect(url_for('sponsors.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('Sponsor/account.html',profile_image=profile_image,form=form)

# List of Blog Posts
@sponsors.route('/<username>')
def sponsor_posts(username):

    page = request.args.get('page',1,type=int)
    sponsor = Sponsor.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=sponsor).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)

    return render_template('sponsor_blog_posts.html',blog_posts=blog_posts,user=user)

src/SDG_Backend/Youths/views.py
from flask import render_template,request,url_for,redirect,Blueprint,flash
from flask_login import login_user,current_user,logout_user,login_required
from .. import db
from ..models import Youth,BlogPost
from .forms import LoginForm,RegistrationForm,UpdateYouthForm
from .picture_handler import add_profile_pic

youths = Blueprint('youths',__name__)

# Register
@youths.route('/register',methods=['GET','POST'])
def register():

    form = RegistrationForm()

    if form.validate_on_submit():
        youth = Youth(email=form.email.data,username=form.username.data,firstname=form.firstname.data,lastname=form.lastname.data,password=form.password.data,
                        phone_number=form.phone_number.data,date_of_birth=form.date_of_birth.data,state_of_origin=form.state_of_origin.data,
                        local_govt=form.local_govt.data,address=form.address.data,education_level=form.education_level.data,reason_for_applying=form.reason_for_applying.data)

        db.session.add(youth)
        db.session.commit()
        flash('Thank you for registering!')
        return redirect(url_for('youths.login'))

    return render_template('Youth/register.html',form=form)

# Login
@youths.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()

    if form.validate_on_submit():
        youth = Youth.query.filter_by(email=form.email.data).first()

        if youth.check_password(form.password.data) and youth is not None:
            login_user(youth)
            flash('Log in Successful!')

            if youth.is_admin:
                return redirect(url_for('core.admin_dashboard'))
            else:
                return redirect(url_for('core.index'))

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('core.index')

            return redirect(next)


        else:
            flash('Invalid email or password.')

    return render_template('Youth/login.html',form=form)

# Logout
@youths.route('/logout')
def logout():

    logout_user()
    flash('You have successfully been logged out.')

    return redirect(url_for('core.index'))

# Account
@youths.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateYouthForm()

    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.bvn = form.bvn.data

        db.session.commit()
        flash('Your Profile has been Updated!')
        return redirect(url_for('youths.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('Youth/account.html',profile_image=profile_image,form=form)

# List of Blog Posts
@youths.route('/<username>')
def youth_posts(username):

    page = request.args.get('page',1,type=int)
    youth = Youth.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=youth).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)

    return render_template('youth_blog_posts.html',blog_posts=blog_posts,user=user)

src/SDG_Backend/templates/analytics.html
<!-- SDG_Backend/templates/analytics.html -->

{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}

<script type="text/javascript">
  var _gauges = _gauges || [];
  (function() {
    var t   = document.createElement('script');
    t.type  = 'text/javascript';
    t.async = true;
    t.id    = 'gauges-tracker';
    t.setAttribute('data-site-id', '5eb66f54d96b5b0e0ead80ed');
    t.setAttribute('data-track-path', 'https://track.gaug.es/track.gif');
    t.src = 'https://d2fuc4clr7gvcn.cloudfront.net/track.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(t, s);
  })();
</script>
{% endblock %}

src/SDG_Backend/templates/base.html
<html lang="en">
<head>
    <title>{{ title }} | SDG Team 109 Project</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="{{ url_for('core.index') }}">SDG Team 109 Project</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                    {% if current_user.username == 'admin' and current_user.email == 'admin@admin.com' %}
                        <li><a href="{{ url_for('core.admin_dashboard') }}">Dashboard</a></li>
                        <li><a href="{{ url_for('admins.list_statuss') }}">Status</a></li>
                        <li><a href="{{ url_for('admins.list_projects') }}">Projects</a></li>
                        <li><a href="{{ url_for('admins.list_sponsors') }}">Sponsors</a></li>
                        <li><a href="{{ url_for('admins.list_youth') }}">Youth</a></li>
                        <li><a href="{{ url_for('blog_posts.create_post')}}">Create Post</a></li>
                    {% elif not current_user.sponsor %}
                        <li><a href="{{ url_for('core.dashboard') }}">Dashboard</a></li>
                        <li><a href="{{ url_for('youths.account') }}">Profile</a></li>
                        <li><a href="{{ url_for('blog_posts.create_post')}}">Create Post</a></li>
                    {% else %}
                        <li><a href="{{ url_for('core.sponsors_dashboard') }}">Sponsor Dashboard</a></li>
                        <li><a href="{{ url_for('sponsors.account') }}">Sponsor Profile</a></li>
                        <li><a href="{{ url_for('blog_posts.create_post')}}">Create Post</a></li>
                    {% endif %}
                    <li><a href="{{ url_for('youths.logout') }}">Logout</a></li>
                    <li><a><i class="fa fa-user"></i>  Hi, {{ current_user.username }}!</a></li>
                  {% else %}
                    <li><a href="{{ url_for('core.index') }}">Home</a></li>
                    <li><a href="{{ url_for('core.info') }}">About Us</a></li>
                    <li><a href="{{ url_for('youths.register') }}">Register</a></li>
                    <li><a href="{{ url_for('youths.login') }}">Login</a></li>
                    <li><a href="{{ url_for('sponsors.register') }}">Sponsor Register</a></li>
                    <li><a href="{{ url_for('sponsors.login') }}">Sponsor Login</a></li>

                  {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
      <div class="push"></div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">

                        <li><a href="{{ url_for('core.index') }}">Home</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        {% if current_user.is_authenticated %}
                            <li><a href="{{ url_for('youths.logout') }}">Logout</a></li>
                        {% else %}
                        <li><a href="{{ url_for('youths.register') }}">Register</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        <li><a href="{{ url_for('youths.login') }}">Login</a></li>
                        {% endif %}
                    </ul>
                    <p class="copyright text-muted small">Copyright © 2020. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

src/SDG_Backend/templates/blog_post.html
<!-- SDG_Backend/templates/Youth/login.html -->

{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block body %}

  <div class="jumbotron">
    <h1>{{ post.title }}</h1>
    <h2>Written by: {{ post.author.username }}</h2>
    <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
    <p>{{ post.text }}</p>

    {% if post.author == current_user %}
    <div>
      <a href="{{ url_for('blog_posts.update',blog_post_id=post.id) }}">Update</a>
      <button type="button" class="btn btn-danger" data-toggle='modal', data-target='#del_modal'>Delete</button>
    </div>
    {% endif %}
  </div>
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete the post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="post">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>


        </div>
      </div>
    </div>
  </div>

{% endblock %}

src/SDG_Backend/templates/create_post.html
<!-- SDG_Backend/templates/Youth/login.html -->

{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <form class="form-group" method="post">
                  {{ form.hidden_tag() }}

                  <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {{ form.title(class="form-control form-control-lg")}}
                  </div>
                  <div class="form-group">
                    {{ form.text.label(class="form-control-label") }}
                    {{ form.text(class="form-control form-control-lg")}}
                  </div>
                  <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info")}}
                  </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

src/SDG_Backend/templates/user_blog_posts.html
<!-- SDG_Backend/templates/Youth/login.html -->

{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block body %}

<div class="container">
  <div class="jumbotron">
    <div align="center">
      <h1>Welcome to the Page for {{user.username}}</h1>
      <img src="{{url_for('static',filename='profile_pics/'+youth.profile_image)}}">
    </div>
  </div>
</div>
{% for post in blog_posts.items %}
  <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
  Written By: <a href="{{url_for('youths.youth_posts',username=post.author.username)}}">{{post.author}}</a>
  <p class="text-muted">Published On: {{post.date.strftime("%Y-%m-%d")}}</p>
  <br>
  <p>{{post.text}}</p>
  <br>
{% endfor %}

<nav aria-label='Page Navigation Example'>
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2)  %}
      {% if blog_posts.page == page_num %}
      <li class='page-item disabled'>
        <a class="page-link" href="{{url_for('youths.youth_posts',username=user.username,page=page_num)}}">{{ page_num}}</a>
      </li>
      {% else %}
      <li class='page-item'>
        <a class="page-link" href="{{url_for('youths.youth_posts',username=user.username,page=page_num)}}">{{ page_num}}</a>
      </li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>

</div>

{% endblock %}